import BlogTemplate from '../../components/layout/BlogTemplate';
import { blogPosts } from '../../data/blog';

export default function GoogleBusinessProfile() {
    const post = blogPosts.find(p => p.id === 'google-business-profile');

    return (
        <BlogTemplate post={post}>
            <p>If you run a local trade business in the UK, your Google Business Profile (GBP) is more important than your actual website. It's the first thing customers see, and it dictates whether you show up in the highly-coveted 'Local Map Pack' at the top of Google.</p>

            <p>Here is the exact setup you need to follow to rank higher than your competitors.</p>

            <h2>1. Title and Accuracy (NAP)</h2>
            <p>Your business name on GBP must match your actual trading name. Do not stuff keywords like "John Smith Plumber Oxford". Google penalises this. However, ensure your Name, Address, and Phone Number (NAP) are exactly the same across your website, Facebook, and Yell.com. Consistency builds trust with Google's algorithm.</p>

            <h2>2. Categories are Crucial</h2>
            <p>Choose your primary category very carefully. If you do 80% boiler repairs, your primary category should be "Heating Engineer" (or similar), not just "Plumber". Add secondary categories for the other services you offer, like "Bathroom Remodeller".</p>

            <h2>3. The Review Engine</h2>
            <p>Reviews are the strongest ranking factor. But getting them is hard because customers forget. The trick is to automate it.</p>
            <ul>
                <li>Send a text message link to your review page exactly 2 hours after you finish the job.</li>
                <li>Explain why it helps: "As a small local business, your review genuinely helps me feed my family."</li>
                <li>Always reply to reviews (even negative ones). It shows Google you are an active, real business.</li>
            </ul>

            <h2>4. Photos Win Trust</h2>
            <p>Don't use stock photos of pristine, American-style kitchens if you're a builder in Leeds. Take genuine, well-lit photos of your work. Upload a mix of:</p>
            <ul>
                <li>Before and after shots</li>
                <li>Your branded van</li>
                <li>You and your team (people buy from people)</li>
            </ul>

            <h2>The Hidden Factor: Call Answering</h2>
            <p>Did you know Google tracks if people try to call you through your profile and you don't answer? It's a poor user experience. If you consistently miss calls, Google will eventually stop showing your profile at the top.</p>
            <p>Using an AI Voice Agent ensures that every single call generated by your perfectly optimised Google profile is answered instantly, protecting your rankings and your revenue.</p>
        </BlogTemplate>
    );
}
